# Plantilla para archivo custom.properties
# Pasos a seguir:
# 1. Copia este archivo en la raíz del proyecto y nómbralo custom.properties
# 2. Remplaza los valores con tus credenciales
# 3. Ejecuta el comando: ./gradlew clean build

# Credenciales de firma para release
APP_STORE_FILE=D\:\\tu_ruta\\archivo.keystore
APP_STORE_PASSWORD=tu_clave
APP_KEY_ALIAS=tu_alias
APP_KEY_PASSWORD=tu_clave

# Clave de API Map de Google
MAPS_API_KEY_DEBUG=Tu_llave_de_mapas_de_google_desarrollo
MAPS_API_KEY_RELEASE=Tu_llave_de_mapas_de_google_producción