# Obliga al proyecto a usar librerias AndroidX en lugar de Support Libraries
android.useAndroidX=true

# Define el estilo oficial de Kotlin (convenciones de codigo)
kotlin.code.style=official

# Hace que las clases R no sean transitivas, mejora tiempos de compilacion en proyectos grandes
android.nonTransitiveRClass=true

# Activa el cache de configuracion de Gradle para acelerar builds repetidos
org.gradle.configuration-cache=true